### ISSUE TITLE
libossia not included in release

### ISSUE THREAD

**Issue by alexdmiller** [bltzr/ofxOscQuery#4]
The README states

> A compiled version of libossia is included in the release.

However, after pulling the repo and attempting to include the addon in an OF project, I see the following error:

```
'ossia-cpp98.hpp' file not found
```

Upon inspection of the ofxOscQuery repo, I see no libossia headers or binaries. Am I missing something? Thanks!

**Comment by bltzr** [comment]
Hi @alexdmiller !

The installation is supposed to be similar to any other ofAddon's installation, and should be a no-brainer:
- download [the Zipped release](https://github.com/bltzr/ofxOscQuery/releases/download/1.0/ofxOscQuery-v1.0.0.zip)
- unzip it in of's addons folder
- and that should be it.

As you can see in the screenshot below, the header is supposed to be there, and the lib for each of the supported OSs as well... 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/113982/72740423-ea041480-3ba5-11ea-9504-e2c91b12b02a.png">

However, as you mention, the lib is not included in the repo, because, each implementation depends on one particular version of libossia - it *should* work with later versions, but we know how this goes with FLOSS...
So, the safest option, if you want to use the repo, is to copy the folders from the release into your repo, and to work from there. 

Does that help ?

**Comment by alexdmiller** [comment]
Whoops, I just totally missed the "releases" tab. I submitted a small PR to add instructions for dummies like me to the README. Thanks a lot!

**Comment by bltzr** [comment]
Thanks for this @alexdmiller !!
